modLoader = "javafml"
loaderVersion = "[43,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "elysiumsync"
version = "${version}"
displayName = "ElysiumSync"
authors = "Brodino"
description = '''

'''
#logoFile = ""

[[dependencies.elysiumsync]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.elysiumsync]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.elysiumsync]]
modId = "architectury"
mandatory = true
versionRange = "[6.5.82,)"
ordering = "AFTER"
side = "BOTH"
